espend_twig_template:
    resource: "@espendTwigTemplateBundle/Resources/config/routing.yml"
    prefix:   /

espend_router_routes:
    resource: "@espendRouterRoutesBundle/Resources/config/routing.yml"
    prefix:   /

espendTranslationDomainBundle:
    resource: "@espendTranslationDomainBundle/Resources/config/routing.yml"
    prefix:   /

post:
    resource: "@espendRouterRoutesBundle/Controller/AnnotationController.php"
    type:     annotation