<?php

namespace espend\Doctrine\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BikeRepository extends EntityRepository
{
    public function getFoo() {}
}
