espend\Doctrine\RelationBundle\Entity\ForeignEntity:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        field_1:
            type: integer
            column: dfdfdsf
    lifecycleCallbacks: {  }
