parameters:


services:
    acme_demo.form.type.gender:
        class: espend\Form\TypeBundle\Form\WeakFooType
        tags:
            - { name: form.type, alias: weak_return_alias  }

    acme_demo_bundle.image_type_extension:
        class: espend\Form\TypeBundle\Extension\WeakFormExtension
        tags:
            - { name: form.type_extension, alias: file }

